baseURL = "https://autom-a.github.io"
title = "AutomA Wiki"

languageCode = "en-us"
defaultContentLanguage = "en"

[params]
    author.name = "AutomA Team"
    description = "This wiki explains how to use AutomA software and how to contribute to it."

    themeVariant = ["zen-light", "zen-dark"]
    themeVariantAuto = [ "zen-light", "zen-dark" ]

    alwaysopen = false
    collapsibleMenu = true
    externalLinkTarget = "_blank"
    disableLandingPageButton = true

    [params.imageEffects]
        border = false
        lightbox = true
        shadow = false


[module]
[[module.imports]]  
    path = "github.com/McShelby/hugo-theme-relearn"

[menu]
    [[menu.shortcuts]]
        name = "<i class='fab fa-fw fa-github'></i>GitHub"
        url = "https://github.com/Autom-A"
        weight = 10

[outputs]
    home = ["HTML", "RSS", "PRINT", "SEARCH"]
    section = ["HTML", "RSS", "PRINT"]
    page = ["HTML", "RSS", "PRINT"]

[languages]
    [languages.en]
        languageName = "English"
    [languages.fr]
        languageName = "Français"
